services:
  sonar:
    image: sonarqube:9.9.3-community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '1'
    #      memory: 512M 
  
  #jenkins:
  #  image: 
  #  depends_on:
  #    - sonar


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: